type NewPost = {
  slug: string;
  publishedAt: '2026-08-18';
  title: string;
  excerpt: string;
  minutes: number;
  sections: { heading: string; body: string }[];
};

const frame = (topic: string, audience: string, decision: string, evidence: string, failure: string, review: string) => [
  { heading: 'Define the operating question', body: `A Philippines-based operations team needs a narrower brief than a broad outsourcing label provides. For ${topic}, start by naming the work arriving in the queue, the record that proves it, and the person who owns the outcome. The purpose is not to transfer every adjacent task. It is to create a dependable lane that a Filipino specialist can perform repeatedly while a named owner retains policy, money, security, and customer commitments. Write the normal case in plain language, then list the facts that make a request unusual. This gives ${audience} a shared starting point and prevents a role from expanding through informal requests. The best brief describes the decision to be supported: ${decision}.`, },
  { heading: 'Design the first lane', body: `Separate preparation from authorization. The specialist can collect inputs, compare them with an approved rule, update a queue, and prepare a concise handoff. The owner should decide when evidence conflicts, when the requested action changes a promise, or when the written procedure is silent. For ${topic}, the first lane should use stable inputs and a visible completion state. Avoid launching with every channel, record type, and exception at once. A small lane makes coaching specific: the reviewer can point to a missing field, an incorrect status, or a late handoff rather than offering general feedback. The Philippines staffing decision becomes safer when the work sample mirrors the actual lane and tests judgment at its boundary.`, },
  { heading: 'Make evidence part of the work', body: `A finished task is more than an answer or a changed field. Record the source checked, the action taken, the unresolved question, and the next owner when the work leaves the normal path. For ${topic}, useful evidence is ${evidence}. Keep the note proportional: copy only what the next person needs, avoid unnecessary personal information, and preserve the original record when a correction is made. A queue that shows only “done” cannot explain rework or teach a new teammate. A short evidence standard also makes timezone handoffs calmer because the next reviewer can see what happened without reconstructing a private conversation.`, },
  { heading: 'Set access and role boundaries', body: `Access should follow the lane, not the title. Begin with named accounts, the smallest useful permissions, approved storage, and a clear route for suspicious messages or uncertain identity. Do not give a Filipino specialist authority merely because the system makes a button available. For ${topic}, keep decisions about ${decision} with the designated owner, and give the specialist a preparation action instead. Document what can be viewed, edited, exported, approved, or communicated externally. Review permissions when the queue changes and close them when the role ends. This separation protects the company and gives the specialist a fair definition of success: accurate operating work within known limits.`, },
  { heading: 'Use a deliberate handoff', body: `A handoff should answer five questions without a meeting: what happened, what was checked, what is still uncertain, what action is requested, and when the next response is due. For ${topic}, do not forward an entire thread and call it context. Summarize the relevant facts, link the source record, identify the rule that was applied, and name the decision owner. If the owner rejects the request, preserve the reason so the next similar case does not restart from zero. If a customer or vendor is waiting, distinguish a promised update from an internal target. Clear handoffs are especially important across Philippines and client time zones because elapsed hours can hide an unowned decision.`, },
  { heading: 'Anticipate the failure mode', body: `The common failure is not always a careless worker. It may be an ambiguous queue, two conflicting sources, an approval rule nobody can find, or a metric that rewards speed while hiding rework. For ${topic}, watch for ${failure}. Create a stop condition for that case and tell the specialist what facts to collect before escalating. Do not coach people to guess in order to keep a queue moving. A safe pause is productive when it prevents an incorrect customer message, an unauthorized change, or an unreconciled record. Capture repeated stops in a small improvement log; the process owner can then decide whether the rule, tool, or role should change.`, },
  { heading: 'Measure quality without false precision', body: `Review output in separate dimensions: completeness, accuracy, timeliness, evidence, and escalation judgment. A high count of completed items does not prove that ${topic} is healthy if records are being corrected later. Use a defined sample, retain the examples, and explain exclusions. Compare like work with like work; an exception-heavy week should not be treated as a normal baseline. The manager can set a review rhythm that starts close and becomes lighter only when the evidence supports it. When the measure changes, record the definition and effective date. This keeps a Philippines operations conversation focused on observable work instead of impressions about effort or personality.`, },
  { heading: 'Run the owner review', body: `The owner review should end with decisions, not a vague status recital. Bring the oldest meaningful items, repeated questions, access concerns, defects, and proposed changes. For ${topic}, ask whether the lane is still narrow enough, whether the source material is current, and whether the escalation path was usable in practice. Record one accountable owner and one due point for each change. The Filipino specialist may propose a clearer field, example, or queue state, but a policy or customer commitment still needs authorized approval. The review becomes valuable when it changes the next week’s operating behavior and leaves a short record that a backup reviewer can understand.`, },
  { heading: 'A practical starting sequence', body: `Start with a written scope, a low-risk sample, and a short access review. Observe the first completed items, correct the instruction where the same question repeats, and expand only one dimension at a time: volume, system access, channel, or exception type. For ${topic}, use ${review} as the first checkpoint. If the lane cannot be explained to a new reviewer in a few minutes, it is not ready for more volume. This sequence respects the value of Filipino operations specialists while keeping the client owner accountable for the rules, evidence, and decisions that make delegated work safe.`, },
];

const specs = [
  ['philippines-operations-shift-handoff', 'Shift handoffs for a Philippines operations team', 'Transfer active work across time zones without losing the decision, evidence, or next deadline.', 'daily queue ownership and unresolved decisions', 'the final note lists a queue count but omits the oldest blocked item', 'a five-item end-of-shift sample with one next-owner check'],
  ['philippines-outsourced-order-cancellation-review', 'Order-cancellation review for Philippines ecommerce operations', 'Prepare cancellation requests with identity, order state, policy evidence, and a controlled approval path.', 'whether the request is routine, restricted, or owner-only', 'a cancellation is treated as valid because a message sounds urgent', 'the request source, order state, policy row, and approval result'],
  ['philippines-outsourced-customer-onboarding-qa', 'Customer-onboarding QA for Philippines operations teams', 'Check onboarding steps for missing inputs, ownership gaps, and safe customer-facing handoffs.', 'whether a new account is ready for the next implementation step', 'a checklist is marked complete while a required dependency remains unknown', 'a sample of completed onboarding records against required fields'],
  ['philippines-offshore-inventory-reconciliation', 'Inventory reconciliation for Philippines support operations', 'Reconcile inventory records without turning an unexplained difference into an unsupported adjustment.', 'which source is authoritative for each inventory state', 'a worker edits the quantity before preserving the comparison evidence', 'a dated exception sample grouped by source mismatch'],
  ['philippines-outsourced-renewal-risk-preparation', 'Renewal-risk preparation for Philippines operations support', 'Prepare renewal follow-up facts while keeping commercial judgment with the account owner.', 'which accounts need an owner decision before a renewal date', 'silence is labeled as churn or a specialist makes a retention promise', 'aging, last contact, open issue, and requested owner action'],
  ['philippines-support-macro-review', 'Support-macro review for Philippines customer service teams', 'Keep response macros accurate, bounded, and connected to the approved knowledge source.', 'when a reusable reply is safe and when a case needs custom review', 'a macro survives a policy change because nobody owns its review date', 'a monthly sample of macro use, edits, and escalations'],
  ['philippines-outsourced-payment-reconciliation', 'Payment reconciliation for Philippines administrative support', 'Prepare payment mismatches with source records and route financial decisions to the right owner.', 'whether two records describe the same payment event', 'a matching amount is assumed to prove a matching transaction', 'a reconciliation log with source keys, period, and unresolved class'],
  ['philippines-operations-change-request-log', 'Change-request logs for Philippines operations teams', 'Control process changes through a visible request, review, decision, and effective-date trail.', 'which proposed change is approved, pending, or rejected', 'an urgent edit reaches the live procedure without an accountable approver', 'a weekly review of age, decision status, and affected guidance'],
  ['philippines-outsourced-content-upload-controls', 'Content-upload controls for Philippines operations support', 'Upload approved operational content while separating formatting work from publication authority.', 'whether a file is ready, approved, and mapped to the correct destination', 'a clean-looking upload hides an incorrect version or audience', 'preflight fields, source version, destination, and reviewer sign-off'],
  ['philippines-customer-support-case-categorization', 'Customer-support case categorization for Philippines teams', 'Create useful case categories that improve routing without pretending every issue fits one label.', 'which category supports the next action and later reporting', 'the first keyword determines the category even when the record says otherwise', 'a boundary-case sample with correction reasons'],
  ['philippines-outsourced-supplier-document-review', 'Supplier-document review for Philippines operations', 'Check supplier documents for completeness and route legal or commercial interpretation.', 'whether the packet is ready for an authorized review', 'a missing signature is buried inside a long attachment thread', 'document type, version, missing item, owner, and due point'],
  ['philippines-remote-operations-backup-plan', 'Backup plans for a Philippines remote operations role', 'Design continuity around queue ownership, records, access, and explicit fallback decisions.', 'what happens when the primary specialist or system is unavailable', 'a backup plan names a person but not the work state or access path', 'a tabletop review of one absence and one system outage'],
  ['philippines-outsourced-calendar-conflict-review', 'Calendar-conflict review for Philippines administrative support', 'Resolve scheduling conflicts with rules, priorities, privacy boundaries, and owner confirmation.', 'which meeting can move and who has authority to choose', 'the coordinator optimizes the calendar without understanding the priority', 'a conflict log showing request, options, decision, and notification'],
  ['philippines-operations-approval-matrix', 'Approval matrices for Philippines operations teams', 'Turn vague approval language into usable action limits for delegated work.', 'which role may prepare, recommend, approve, or communicate', 'one person is expected to both check evidence and approve the exception', 'a quarterly review of real cases against the matrix'],
  ['philippines-outsourced-customer-data-correction', 'Customer-data correction workflow for Philippines support', 'Correct customer records with authority checks, original-value protection, and visible review.', 'when a requested correction is verified and permitted', 'a specialist overwrites the old value without preserving why it changed', 'sampled corrections with request source and before-after evidence'],
  ['philippines-operations-training-records', 'Training records for Philippines operations specialists', 'Track role training as observable capability evidence rather than a list of completed meetings.', 'whether a specialist can perform the approved lane and escalate its edge cases', 'attendance is treated as proof of readiness', 'scenario results, reviewer notes, and a next practice item'],
  ['philippines-outsourced-delivery-exception-review', 'Delivery-exception review for Philippines ecommerce support', 'Prepare delivery exceptions with event history, customer impact, and permitted next actions.', 'whether the case is a carrier delay, record mismatch, or owner decision', 'one tracking scan is treated as the whole delivery story', 'exception age, latest evidence, promised update, and owner'],
  ['philippines-support-queue-priority-calibration', 'Support-queue priority calibration for Philippines teams', 'Keep queue priority consistent by defining impact, urgency, dependency, and escalation.', 'which item should move first and why', 'the loudest message becomes the highest priority without a rule', 'a weekly review of overrides and their documented reasons'],
  ['philippines-outsourced-contract-renewal-coordination', 'Contract-renewal coordination for Philippines operations', 'Coordinate renewal dates and documents while keeping negotiation and commitment decisions with owners.', 'which renewal packet is complete and what decision is missing', 'a coordinator sends a commitment because a deadline is near', 'renewal stage, evidence, owner, and next contact date'],
  ['philippines-operations-incident-note-taking', 'Incident note-taking for Philippines operations teams', 'Capture operational incidents clearly enough for response, review, and later prevention.', 'what happened, what was contained, and what remains uncertain', 'notes mix facts, assumptions, and blame into one timeline', 'a closed-incident review for evidence, actions, and follow-up'],
  ['philippines-outsourced-knowledge-gap-register', 'Knowledge-gap registers for Philippines support teams', 'Turn unanswered recurring questions into owned knowledge work without inventing policy.', 'which missing answer needs an owner and a safe interim route', 'a specialist fills a gap with an answer copied from a similar case', 'gap age, frequency, risk, owner, and approved resolution'],
  ['philippines-operations-work-sample-design', 'Work-sample design for Philippines operations hiring', 'Test real operating judgment with bounded samples, evidence requirements, and fair scoring.', 'whether a candidate can perform the role’s normal lane and recognize its limits', 'a polished generic exercise tests writing but not workflow judgment', 'sample accuracy, record quality, escalation choice, and explanation'],
  ['philippines-outsourced-offshore-service-review', 'Service reviews for a Philippines outsourced operations lane', 'Review delegated service work through evidence, decisions, risks, and scope changes.', 'whether the operating lane should continue, change, or stop', 'a meeting discusses activity without examining outcomes or ownership', 'a compact review pack with sample work and open decisions'],
] as const;

export const august18BlogPosts: NewPost[] = specs.map(([slug, title, excerpt, audience, failure, review], index) => ({
  slug,
  publishedAt: '2026-08-18',
  title,
  excerpt,
  minutes: 12,
  sections: frame(title.toLowerCase(), audience, 'an exception, approval, policy change, or customer commitment', 'the source record, rule applied, owner requested, and time of the next action', failure, review).map((section, sectionIndex) => ({
    ...section,
    body: `${section.body} This is section ${sectionIndex + 1} of the ${title} guide; keep its example attached to the relevant record rather than replacing it with a general status label.`,
  })),
}));
