const DATE = '2026-09-08';
const HERO = '/philippines-operations-team.svg';

export const september8ResearchPosts = [
  { slug: 'offshore-queue-age-decision-latency-study', title: 'Queue age and owner decision latency in offshore operations', excerpt: 'A bounded study design for separating specialist handling time from delays waiting for authorized decisions.', date: DATE, hero: HERO, body: [
    'Research question and scope: how much of a defined operations queue\'s elapsed age occurs while work is ready for a specialist, actively handled, or waiting for an authorized owner? The unit of analysis is one ticket in one declared workflow and observation window. The study does not estimate the productivity of all offshore teams or the quality of any individual worker.',
    'Methodology: freeze state definitions before collection, retain every timestamp and transition source, and sample tickets across work type, consequence, and outcome. Calculate elapsed time in ready, active, waiting-for-information, waiting-for-owner, and completed states. Audit a random subset against source-system history and report missing or contradictory events instead of imputing precision.',
    'Evidence and inference limits: observed state durations can locate where elapsed time accumulated, but they cannot by themselves establish why an owner waited or whether a shorter decision would have produced a better outcome. Queue configuration, working hours, reopened tickets, and parallel work are competing explanations that must remain visible.',
    'Reputable source framework: NIST describes measurement as part of cybersecurity governance and improvement; the U.S. Government Accountability Office provides evidence-oriented evaluation guidance; and the Project Management Institute maintains practice standards relevant to work and risk tracking. These sources inform method, not a benchmark for this company. Sources: https://www.nist.gov/cyberframework; https://www.gao.gov/products/gao-12-208g; https://www.pmi.org/standards.',
    'Limitations: administrative timestamps can reflect automation rather than human attention, status changes may be late, small samples may miss rare exceptions, and privacy rules may constrain record detail. Report the system, timezone, work calendar, definitions, exclusions, missing-data rate, sample method, and observation dates.',
    'Evidence-led conclusion: a state-duration study can distinguish handling and decision waits when definitions and transition evidence are preserved. It supports a narrower improvement question; it does not assign blame or prove that offshore delivery caused the delay. Retrieved 2026-09-08.' ] },
  { slug: 'philippines-crm-merge-error-reversibility-research', title: 'Reversibility evidence for CRM account merges in Philippines support', excerpt: 'A research protocol for testing whether approved duplicate-account merges preserve identity, consent, and connected records.', date: DATE, hero: HERO, body: [
    'Research question and scope: under a declared CRM configuration, which pre-merge evidence and post-merge checks predict whether a duplicate-account merge can be verified or safely reversed? The unit is one approved merge pair. The study excludes identity adjudication and does not generalize across every CRM product.',
    'Methodology: define critical fields and connected objects before sampling. For each pair, preserve candidate-match evidence, approval, surviving-record choice, field-resolution rules, relationship counts, consent state, owner, and audit identifier. Run a staged test where possible, then compare the approved snapshot with the live post-merge record and restoration procedure.',
    'Inference limits: a matching field count does not prove semantic correctness, and a successful rollback test does not guarantee recovery after later automation. Separate observed preservation, owner-approved conflict resolution, and inferred identity. Record false-positive candidates as well as completed merges.',
    'Reputable sources: NIST SP 800-53 provides controls for audit records, configuration, and contingency planning; NIST\'s Privacy Framework frames data-processing risk; and the U.S. Federal Trade Commission publishes business guidance for protecting personal information. Sources: https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final; https://www.nist.gov/privacy-framework; https://www.ftc.gov/business-guidance/privacy-security.',
    'Limitations: vendor audit features differ, integration effects may occur after observation, consent rules vary by jurisdiction and purpose, and staged data may not reproduce production complexity. Report software version, integration inventory, access model, sampling rule, observation window, and every untested recovery dependency.',
    'Evidence-led conclusion: approved snapshots plus relationship, consent, audit, and recovery checks create stronger merge evidence than a duplicate score alone. The protocol can reveal control gaps but cannot authorize a merge or determine legal identity. Retrieved 2026-09-08.' ] },
  { slug: 'offshore-payroll-input-completeness-research', title: 'Payroll input completeness research for offshore support lanes', excerpt: 'A scoped method for measuring missing, late, conflicting, and unapproved payroll inputs without evaluating pay policy.', date: DATE, hero: HERO, body: [
    'Research question and scope: for one payroll period and declared employee population, what proportion of expected input records are present, timely, internally consistent, and supported by the required approval at cutoff? The study evaluates preparation evidence, not compensation fairness, legal compliance, or payroll-provider accuracy.',
    'Methodology: create an expected-input register from authorized rosters and source systems, define cutoff and approval rules in advance, and classify each input as complete, missing, late, conflicting, duplicate, or approval-pending. Reconcile a sampled subset to original time, leave, and change records. Publish counts and denominators separately by input type.',
    'Inference limits: completeness does not establish legal correctness, and late data may reflect an approved exception. The method can identify where evidence is absent or conflicting but cannot determine tax, wage, benefit, or employment-law treatment. Those questions stay with qualified owners.',
    'Reputable sources: the U.S. Department of Labor maintains recordkeeping guidance under federal labor standards; the Internal Revenue Service publishes employment-tax recordkeeping guidance; and NIST SP 800-53 addresses access control and audit records. Sources: https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping; https://www.irs.gov/businesses/small-businesses-self-employed/employment-tax-recordkeeping; https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final.',
    'Limitations: applicable requirements vary by jurisdiction, worker status, and organization; source rosters may themselves be incomplete; corrections after cutoff can change the result; and sensitive-data controls limit public reproducibility. Report jurisdictional scope, systems, population rule, cutoff, classifications, reviewer, and correction window.',
    'Evidence-led conclusion: a frozen expected-input register makes payroll preparation gaps measurable without turning the support team into the policy authority. Results support targeted owner review and should not be presented as a compliance opinion. Retrieved 2026-09-08.' ] },
  { slug: 'philippines-support-escalation-delivery-research', title: 'Escalation delivery and acknowledgement research for Philippines support', excerpt: 'A reproducible protocol for distinguishing sent, delivered, acknowledged, decided, and implemented support escalations.', date: DATE, hero: HERO, body: [
    'Research question and scope: in a named support workflow, how reliably do consequential escalations progress through sent, delivered, acknowledged, decided, and implemented states within declared targets? The unit is one escalation event. The study does not judge the substantive quality of owner decisions unless a separate rubric is approved.',
    'Methodology: freeze trigger, destination, backup path, state definitions, and time targets before selecting a stratified sample. Reconstruct events from ticket history and approved messaging logs, then verify implementation in the source system. Use exact counts for missing destinations, unacknowledged deliveries, late decisions, and actions without implementation evidence.',
    'Inference limits: communication logs can show observed transitions but not attention, intent, or decision difficulty. High-severity cases may appropriately take longer and automated receipts may not represent human acknowledgement. Analyze severity and owner path separately rather than treating one average as a universal benchmark.',
    'Reputable sources: NIST Cybersecurity Framework 2.0 covers governance, response, and improvement outcomes; CISA publishes incident-response resources; and ISO describes the ISO 10002 complaints-handling standard. Sources: https://www.nist.gov/cyberframework; https://www.cisa.gov/topics/cyber-threats-and-advisories/incident-detection-response-and-prevention; https://www.iso.org/standard/71580.html.',
    'Limitations: the cited frameworks are not evidence that every support escalation is a security incident or formal complaint. Tool retention, timezone rules, manual status updates, and private channels may reduce completeness. Report exclusions, missing-log rates, target definitions, sampling method, and any reviewer disagreement.',
    'Evidence-led conclusion: state-specific evidence reveals whether escalation failure occurs before acknowledgement, decision, or implementation. It can guide workflow changes without shifting authority to the Philippines support coordinator or claiming causation from timing alone. Retrieved 2026-09-08.' ] },
  { slug: 'offshore-article-image-integrity-study', title: 'Rendered image integrity study for offshore article publishing', excerpt: 'A deployment-tied method for verifying hero and social images across a bounded daily publication batch.', date: DATE, hero: HERO, body: [
    'Research question and scope: for a frozen daily article manifest and deployed revision, do hero and Open Graph image references resolve successfully, match approved inventory, and render with the intended page identity? The unit is one canonical article route. The method does not measure visual preference, search ranking, or licensing compliance beyond the supplied approval record.',
    'Methodology: record route, family, title, canonical, approved asset path, expected media type, dimensions, and file hash before build. After deployment of the exact revision, request the article, hero URL, and Open Graph URL directly without accepting hidden redirects. Parse metadata, capture HTTP status and content type, and compare referenced assets with the manifest.',
    'Inference limits: HTTP 200 proves availability at one observation time, not ongoing delivery or correct rights. Matching paths and hashes prove file identity, not whether a crop communicates the intended concept. Responsive visual inspection and editorial approval remain separate gates.',
    'Reputable sources: the Open Graph protocol defines image metadata; the WHATWG HTML standard describes image and link processing; WCAG 2.2 provides text-alternative and visual presentation criteria; and RFC 9110 defines HTTP semantics. Sources: https://ogp.me/; https://html.spec.whatwg.org/multipage/images.html; https://www.w3.org/TR/WCAG22/; https://www.rfc-editor.org/rfc/rfc9110.',
    'Limitations: caches and content-delivery networks can change observations, SVG intrinsic sizing behaves differently from raster files, screenshot tools sample particular viewports, and a page can pass mechanically while its image is contextually weak. Report timestamp, viewport, user agent, cache behavior, revision, and manual-review owner.',
    'Evidence-led conclusion: manifest, response, metadata, and responsive-render evidence together provide a reproducible image-integrity gate. The study supports OffshoreOutsourcingCompany.com daily routines but cannot replace rights review or editorial judgment. Retrieved 2026-09-08.' ] },
] as const;
