type ResearchPost = { slug: string; date: '2026-08-17'; title: string; excerpt: string; body: string[]; relatedService?: { label: string; href: string; body: string } };

const evidenceNote = (topic: string, boundary: string, sources: string) => [
  `Evidence scope and method: this ${topic} study is designed for a buyer evaluating a Philippines-based operations role, not for ranking a country or predicting every team. Use a dated sample from the actual queue, split by ordinary work, owner-dependent work, and exceptions. Preserve the source record, the inclusion rule, the denominator, and the time zone. A sample of 30 items can expose missing fields and decision boundaries; it cannot establish a universal benchmark. Report counts beside percentages and distinguish business time from time waiting for an owner or an external system.`,
  `Interpretation should proceed in three steps. First state what the records show. Next state the narrow operational inference that follows. Finally name the alternatives that remain possible. A late item may reflect incomplete intake, a policy decision, capacity, or a source-system delay. A Philippines specialist can organize evidence and identify the next question, while the accountable owner decides policy, money, security, legal, customer promises, and access. Do not turn a clean administrative measure into a claim about business outcome.`,
  `For implementation, define the accepted input, approved source, expected output, evidence of completion, stop condition, and escalation destination before expanding access. Test with sanitized or low-risk records when the role boundary is still being evaluated. Review the first sample with a second person who can reproduce the classification. Record disagreements instead of forcing consensus; disagreement may show that the rubric or source is unclear. Keep named accounts, least privilege, minimum necessary data, and an effective review date.`,
  `Limitations and conclusion: this analysis does not prove legal compliance, customer satisfaction, causation, or the suitability of any individual. It is a bounded decision aid. The useful conclusion is whether the role should remain narrow, receive clearer evidence requirements, receive another sample, or be escalated to an authorized owner. Recheck after a policy, system, customer segment, or seasonal change. Sources: ${sources}. Retrieved 2026-08-17.`,
];

export const august17ResearchPosts: ResearchPost[] = [
  { slug: 'philippines-outsourced-approval-latency-study', date: '2026-08-17', title: 'Approval latency in Philippines operations support: where decisions wait', excerpt: 'A research study on separating preparation time from owner-decision time when a Philippines support lane handles approval-dependent work.', body: [
    'Research question: when an outsourced operations request appears slow, how much of the elapsed time belongs to preparation and how much belongs to an unanswered owner decision? This distinction matters because a specialist may collect evidence quickly while a policy, finance, or account owner is unavailable. Measure request arrival, completeness, first preparation, escalation, owner response, and final disposition as separate events. A single “turnaround time” number hides the point where work actually stopped.',
    'Use cohorts rather than one blended average. Separate routine requests with a published rule from exceptions, incomplete submissions, and requests requiring more than one owner. For each cohort, record the number of handoffs, missing inputs, clarification cycles, time in the specialist queue, and time in the owner queue. A median can describe the typical case, while the oldest cases reveal control failures. Keep the original timestamps and define whether weekends, holidays, and time-zone differences count.',
    'The buyer-facing finding is that role design improves when decision latency is visible rather than charged to the person preparing the packet. A Philippines operations specialist can check required fields, link evidence, summarize the requested choice, and remind the designated owner. The specialist should not approve an exception simply because the request has aged. The record should state the exact decision, the impact of waiting, the evidence already checked, and the next review point.',
    'Test the measure on one real process using a historical sample and a current sample. Compare missing-decision fields, returned packets, repeated reminders, and items closed without a recorded decision. If latency falls after a clearer request format, that supports an operational association, not proof that formatting caused the change. Look for simultaneous changes in staffing, policy, system routing, and request mix before drawing a stronger conclusion.',
    ...evidenceNote('approval-latency', 'approval authority or a customer commitment', 'https://www.nist.gov/cyberframework; https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees; https://www.cisa.gov/audiences/small-and-medium-businesses')
  ] },
  { slug: 'philippines-outsourced-rework-cause-study', date: '2026-08-17', title: 'Rework causes in Philippines back-office operations: evidence beyond error counts', excerpt: 'How to distinguish unclear intake, source defects, instruction gaps, and execution mistakes in delegated back-office work.', body: [
    'Research question: what explains repeated rework in a Philippines back-office queue, and which causes can the operating design actually change? Counting corrected items is useful but incomplete. A correction may result from an ambiguous request, a stale source, a missing field, a system limitation, a reviewer preference, or an incorrect action. Classify the first observable cause before coaching the person who touched the record. Otherwise the organization may train around a broken input or conflicting rule.',
    'Build a cause taxonomy with examples and an “unknown” category. Sample completed items and compare the original request, source record, instruction version, output, reviewer note, and correction. Record the denominator by work type and the severity or consequence of the rework. A 10 percent correction rate in a new, complex lane should not be interpreted the same way as 10 percent in a stable data-entry lane. Keep changes to the taxonomy dated so successive samples remain comparable.',
    'A useful role boundary gives the specialist permission to flag a defect without assigning blame. The specialist can preserve the original value, identify the conflicting source, describe the missing context, and route the question. The process owner decides whether to change the form, source, instruction, system field, or approval rule. Silent correction may make the queue look cleaner while removing the evidence needed to prevent recurrence.',
    'Run a before-and-after review only when the intervention is explicit. If a new instruction is introduced, note its effective date, affected categories, training exposure, and any concurrent system change. Measure rework with accuracy, completion, escalation, and time-to-decision. A lower rework count can be misleading if reviewers stopped sampling or if difficult items were excluded. The decision should be whether to narrow scope, repair an input, or continue controlled observation.',
    ...evidenceNote('rework-cause', 'a policy exception, source correction, or access change', 'https://www.nist.gov/cyberframework; https://www.ftc.gov/business-guidance; https://www.sba.gov/business-guide/manage-your-business')
  ] },
  { slug: 'philippines-outsourced-case-mix-study', date: '2026-08-17', title: 'Case-mix analysis for Philippines customer support staffing decisions', excerpt: 'A bounded method for learning whether a support queue changed in volume, complexity, or owner dependency.', body: [
    'Research question: did a customer-support queue become larger, more complex, or more dependent on owner decisions? Volume alone cannot answer it. Group cases by issue type, channel, customer impact, required evidence, number of transfers, and whether the specialist could resolve the request under the published rule. The result helps a buyer decide whether to change scope or improve routing without claiming that a location or team caused the pattern.',
    'Define the case unit carefully. A customer may send several messages about one issue, while one message may contain several independent requests. Choose a linkage rule and review false matches. For each cohort, report eligible cases, reopened cases, escalation count, owner-wait time, and recontact within a stated window. Compare like periods and note launches, outages, policy changes, holidays, and coverage changes. A blended weekly average can hide a small high-risk cohort.',
    'The role should make complexity legible. A Philippines support specialist can tag a case using approved definitions, preserve the customer’s request, identify missing evidence, and prepare a handoff. Tagging is not the same as deciding severity, granting a remedy, or diagnosing a product issue. If the taxonomy does not fit a case, record the mismatch rather than forcing the case into a convenient category.',
    'Use a sample review to validate the categories. Ask a second reviewer to classify the same records and discuss disagreements. Then compare the queue shape with outcomes such as recontact, reopen, or unresolved escalation, while keeping causal language modest. The study can show that a lane needs specialist coverage or clearer owner access; it cannot by itself determine a staffing ratio or guarantee a service result.',
    ...evidenceNote('case-mix', 'customer remedy, complaint, security, or policy judgment', 'https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm; https://www.ftc.gov/business-guidance; https://www.nist.gov/privacy-framework/privacy-framework')
  ], relatedService: {
    label: 'Review Customer Support Operations',
    href: '/services/customer-support-operations',
    body: 'Use this service guide when case mix shows that routine customer work needs a clearer queue, source list, and owner handoff. Keep remedies, complaints, security questions, and policy exceptions with the person who can approve them.'
  } },
  { slug: 'philippines-outsourced-handoff-rework-study', date: '2026-08-17', title: 'Handoff rework between Philippines support and owner teams', excerpt: 'What repeated returns of delegated work reveal about context, authority, and the design of a cross-team handoff.', body: [
    'Research question: why does work return after a Philippines support specialist hands it to an owner or another queue? A returned item may lack evidence, request the wrong decision, contain an unrecognized exception, or simply be routed to the wrong owner. Treat the return as an observable event rather than as proof that the first person failed. Preserve both the sent packet and the receiving response so the study can compare the request with the actual decision need.',
    'Measure handoff acceptance, return reason, clarification count, time to acceptance, and whether the customer or internal requester had to repeat information. Segment by process, channel, owner, and risk class. Define acceptance as the receiving owner acknowledging the current state and requested action, not merely opening the record. Review the oldest returns separately; aging can reveal unavailable authority or a missing backup path.',
    'The operating implication is specific: a good handoff carries state, not a transcript. It should name the request, confirmed facts, evidence links, action already taken, open uncertainty, requested decision, owner, and due point. A specialist may prepare this packet and follow up. The specialist should not fill a missing policy with a confident answer or convert a proposed option into an approved commitment.',
    'Pilot one revised handoff field or definition at a time. Compare return categories in a pre-change and post-change sample, and annotate changes in owner coverage or request mix. If returns fall, check whether records are being closed earlier or whether the receiving team has changed its review behavior. The stronger finding is reproducible improvement in acceptance quality, not a lower count on its own.',
    ...evidenceNote('handoff rework', 'an owner decision, customer commitment, or exception approval', 'https://www.nist.gov/cyberframework; https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees; https://www.cisa.gov/audiences/small-and-medium-businesses')
  ] },
  { slug: 'philippines-outsourced-record-completeness-study', date: '2026-08-17', title: 'Record completeness in Philippines operations support', excerpt: 'How to test whether a record contains enough evidence for the next owner to act without confusing completeness with correctness.', body: [
    'Research question: what makes an operational record complete enough for its next action? Completeness is not the same as accuracy, approval, or a finished outcome. Define the fields needed for the specific process: request, source, subject, date, current state, evidence, owner, requested action, and exception status. A broad field list can create noise, while a narrow list can omit the one fact needed to make a safe decision.',
    'Study records by process and state. A new intake may need context and urgency; an owner review may need policy evidence and options; a completed item may need the changed field and reviewer. Count missing fields and also test whether the present fields are current and traceable. Report the sample frame, period, excluded records, and denominator. Do not claim that a complete record proves the underlying business action was correct.',
    'A Philippines operations specialist can check presence, format, source link, and effective date against the approved definition. When two sources conflict, the specialist should record the conflict and route it. They should not manufacture a value from a similar case, remove an inconvenient field, or mark a record complete merely because the queue is old. The owner remains responsible for policy interpretation and consequential choices.',
    'Use a small inter-reviewer exercise to check whether “complete” means the same thing to different reviewers. If agreement is weak, improve examples and boundary cases before using the measure for performance decisions. Recheck after one cycle and inspect newly created records, not only the backlog. A cleanup that improves yesterday’s records while new records remain incomplete is not a durable control.',
    ...evidenceNote('record completeness', 'truth of the business event or approval of a consequential action', 'https://www.nist.gov/privacy-framework/privacy-framework; https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business; https://www.cisa.gov/resources-tools/resources')
  ] },
  { slug: 'philippines-outsourced-queue-switching-study', date: '2026-08-17', title: 'Queue switching and interruption in Philippines operations work', excerpt: 'A research approach for deciding whether task switching is creating hidden rework in a delegated operations lane.', body: [
    'Research question: does frequent switching between queues create measurable rework, missed commitments, or weaker evidence in Philippines operations support? Switching is not automatically harmful; urgent customer work may require interruption. The study should distinguish planned movement, escalation, reassignment, and unplanned context switching. Record the task state before and after the switch, the reason, the owner, and whether the original work was resumed with its evidence intact.',
    'Use event data cautiously. Count switches per item, time to resume, missing fields after resumption, correction, reopen, and deadline miss. Compare similar work with different switching patterns, while noting that difficult cases may cause both more switches and more rework. If the system logs are incomplete, state that as a measurement limitation. Do not infer individual productivity from activity events without understanding the work and its dependencies.',
    'A buyer can use the findings to refine role scope and coverage. A specialist may maintain a bounded queue, record an interruption reason, and return to the prior state. A manager or owner should decide priority conflicts, emergency coverage, and whether a case can be paused. The role should not self-authorize access to another queue just to avoid an escalation path.',
    'Test one scheduling or routing change on a defined cohort. Keep the task definitions and observation window stable, then inspect both speed and evidence quality. An apparent speed gain may come from skipping documentation; a lower switch count may come from leaving urgent work waiting. Report tradeoffs rather than selecting the most flattering measure.',
    ...evidenceNote('queue switching', 'priority conflicts, emergency coverage, and scope expansion', 'https://www.bls.gov/ooh/office-and-administrative-support/home.htm; https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees; https://www.nist.gov/cyberframework')
  ] },
  { slug: 'philippines-outsourced-source-conflict-study', date: '2026-08-17', title: 'Conflicting source records in Philippines support operations', excerpt: 'How to research disagreements between systems, customer statements, and internal documents before delegating reconciliation work.', body: [
    'Research question: when two operational sources disagree, what evidence allows a Philippines support specialist to prepare a safe resolution without silently choosing one? First name the sources, their purpose, effective period, owner, and expected relationship. A customer message, a system status, and an approved policy can all be true while answering different questions. The study should classify the conflict rather than treat the newest-looking field as authoritative.',
    'Sample conflicts by source pair and issue type. Useful categories include timing difference, stale record, duplicate event, identity mismatch, policy ambiguity, and genuine missing evidence. Preserve the original values, timestamps, and links. Record which source was consulted and what question remains. A reconciliation prepared without a visible source trail is difficult for an owner to review and easy for a later operator to misunderstand.',
    'The delegated lane can compare, annotate, and route. It should not edit a source to make the records agree, override an account hold, promise a correction, or decide that a customer statement is false. The process owner should define precedence where possible and identify the next owner for exceptions. When precedence is absent, the right result is a bounded question and a pause on the risky action.',
    'Evaluate the method using historical or sanitized examples that include timing and duplicate cases. Have another reviewer reproduce the classification. Track time to resolution, returned packets, silent edits discovered, and conflicts that remain unresolved. Improvement means better evidence and safer decisions, not merely fewer visible discrepancies.',
    ...evidenceNote('source conflict', 'a source-of-truth decision, identity issue, or policy interpretation', 'https://www.nist.gov/cyberframework; https://www.nist.gov/privacy-framework/privacy-framework; https://www.ftc.gov/business-guidance')
  ] },
  { slug: 'philippines-outsourced-escalation-quality-study', date: '2026-08-17', title: 'Escalation quality in Philippines customer support', excerpt: 'A bounded study of whether escalations contain the evidence and decision request an owner actually needs.', body: [
    'Research question: what separates a useful escalation from a transfer that merely moves an unresolved case? Define quality through observable fields: customer or case context, confirmed facts, evidence, impact, policy reference, requested decision, owner, and deadline. The right fields depend on the issue. A security concern needs different evidence from a delivery exception. Do not reward long narratives that bury the one choice the owner must make.',
    'Sample escalations by reason and outcome. Record missing evidence, returned packets, repeated questions, time to owner acceptance, decision latency, and customer recontact where available. Read a sample end to end to verify whether the summary matches the source. A low return rate can be misleading if owners resolve cases informally or if difficult cases are closed without a documented decision.',
    'The Philippines support role can prepare a concise, factual packet and keep the case current as new evidence arrives. It should label customer statements, system observations, and proposed options separately. It should not decide whether a complaint is valid, authorize a refund, change security status, or make a policy exception. Clear escalation boundaries protect the customer and the owner as well as the specialist.',
    'Compare a baseline with one revised escalation definition. Keep issue mix, owner coverage, and review period visible. If acceptance improves, check whether the owner received better evidence or simply lowered the review threshold. The practical result should be a narrower, more reproducible handoff with a named decision owner and a clear stop condition.',
    ...evidenceNote('escalation quality', 'complaints, money, security, policy exceptions, or customer promises', 'https://www.ftc.gov/business-guidance; https://www.nist.gov/cyberframework; https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm')
  ] },
  { slug: 'philippines-outsourced-access-expiry-study', date: '2026-08-17', title: 'Access-expiry evidence for Philippines operations roles', excerpt: 'How to determine whether delegated access is reviewed and removed when the work, owner, or role changes.', body: [
    'Research question: can a buyer show that access for a Philippines operations role remains aligned with current work and is removed when the need ends? An access list alone is not enough. Link system, account, role, purpose, approver, review date, expiry trigger, and offboarding evidence. Separate access granted from access used, and do not assume that unused access is harmless when it remains available.',
    'Review a sample across systems and role changes. Look for shared accounts, stale approvals, missing review dates, permissions broader than the task, and accounts that remained active after a transfer or end of work. Consider automated events and logging limits before classifying an anomaly. A missing log is a control limitation, not proof that access was misused or safe.',
    'The operations specialist can maintain an access register, prepare review evidence, and flag a mismatch. The system or security owner approves permissions, handles privileged access, and decides remediation. The role should not request broad access for convenience or deactivate another person’s account without authority. Use named accounts, multi-factor authentication, least privilege, and a documented trigger for review.',
    'Test the review with a small set of systems and a recent role change. Measure stale approvals, unexplained permissions, review completion, and time to correction. Recheck after the next workflow or ownership change. The result is an evidence-backed access decision, not a security certification or a claim that any staffing model is inherently safe.',
    ...evidenceNote('access expiry', 'permission approval, privileged action, or offboarding authority', 'https://www.nist.gov/cyberframework; https://www.nist.gov/privacy-framework/privacy-framework; https://www.cisa.gov/stopransomware')
  ] },
  { slug: 'philippines-outsourced-coverage-gap-study', date: '2026-08-17', title: 'Coverage gaps in Philippines support operations', excerpt: 'A study method for finding uncovered queue states during absences, handoffs, holidays, and owner unavailability.', body: [
    'Research question: which support commitments lack an accountable owner when normal coverage changes? Coverage is not simply the number of people online. Map queue, time window, expected action, backup owner, source of authority, and escalation path. Include work waiting on an owner because that queue can remain uncovered even when a specialist is actively monitoring it.',
    'Review a defined period containing ordinary days and at least one planned coverage change. Compare incoming work, response or acknowledgement, aging, missed commitments, reassignments, and unresolved exceptions by queue. Mark whether the gap came from missing backup, unclear priority, access dependency, time-zone overlap, or an owner decision. Keep business hours and calendar dates explicit.',
    'A Philippines support specialist can monitor the agreed lane, record the last known state, and prepare a handoff before coverage changes. The manager or owner should decide emergency priorities, policy exceptions, customer promises, and access changes. Coverage planning should not be used to imply that one person can safely absorb every queue or that availability equals authority.',
    'Evaluate one coverage plan against the previous state, but avoid treating a single quiet period as proof. Include a scenario with an urgent exception and a scenario with incomplete context. Measure whether the backup could find the current source, identify the next owner, and preserve commitments. The useful conclusion is where a documented backup or escalation rule is missing.',
    ...evidenceNote('coverage gaps', 'emergency prioritization, policy exceptions, and access changes', 'https://www.bls.gov/ooh/office-and-administrative-support/home.htm; https://www.sba.gov/business-guide/manage-your-business; https://www.cisa.gov/audiences/small-and-medium-businesses')
  ] },
  { slug: 'philippines-outsourced-operator-judgment-study', date: '2026-08-17', title: 'Operator judgment in Philippines support roles: testing safe stops', excerpt: 'How to assess whether a delegated specialist recognizes uncertainty and escalates instead of improvising authority.', body: [
    'Research question: what evidence shows that a Philippines support specialist can recognize the boundary between a routine action and an owner decision? Speed and polished writing do not answer it. Build a set of low-risk, incomplete, conflicting, and boundary-case scenarios using sanitized data. Ask the participant to identify the approved source, state what is known, name what is missing, and choose the next permitted action.',
    'Score dimensions separately: source use, factual accuracy, evidence capture, question quality, stop-condition recognition, and escalation destination. A person who pauses and asks a precise question may be safer than one who completes a plausible action from memory. Record the scenario assumptions and rubric version. Do not present a simulation score as proof of live performance or as a judgment about a nationality or location.',
    'Role design matters as much as individual judgment. Provide clear examples of actions the specialist may perform and actions that remain owner-controlled, including customer remedies, financial changes, security decisions, legal interpretation, and policy exceptions. Give the specialist a way to preserve evidence while waiting. Training should explain why the boundary exists, not only provide a script to memorize.',
    'Repeat a small sample after several working days and compare the error categories, not just the total score. Changes in guidance, case mix, or reviewer behavior can affect the result. The buyer should use the finding to narrow scope, clarify sources, or request owner review. It should not be used to promise flawless judgment, guaranteed outcomes, or automatic authority expansion.',
    ...evidenceNote('operator judgment', 'customer, financial, security, legal, or policy authority', 'https://www.nist.gov/cyberframework; https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees; https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm')
  ] },
];
