type ResearchPost = { slug: string; date: '2026-08-21'; title: string; excerpt: string; hero: string; body: string[] };

const commonSources = ['https://www.nist.gov/cyberframework', 'https://www.nist.gov/privacy-framework/privacy-framework', 'https://www.cisa.gov/audiences/small-and-medium-businesses', 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'];

export const august21ResearchPosts: ResearchPost[] = [
  {
    slug: 'philippines-outsourced-queue-aging-evidence-study', date: '2026-08-21', hero: '/research-aug21-heroes/queue-aging-evidence.png',
    title: 'Queue-aging evidence for Philippines outsourced operations', excerpt: 'When does an old outsourced queue item represent a control risk rather than ordinary elapsed time?',
    body: [
      `Research question: when does age in a Philippines outsourced operations queue indicate a control risk rather than ordinary elapsed time? The question matters because a single age number blends work that is actively being prepared, work waiting for a requester, work waiting for an owner decision, and work that has no accountable next action. This study examines one defined queue, one observation window, and a stratified sample of routine, paused, escalated, and completed records. It does not compare countries, suppliers, or individual workers. Its decision purpose is narrower: determine which queue states can remain within a delegated support lane and which states require an owner response or a change to the operating design.`,
      `The method begins by defining the clock. Record when the request became eligible, when complete inputs arrived, when preparation started, when the item entered a hold, when an owner was asked to decide, and when the disposition was recorded. Declare the time zone and business-calendar rule. Calendar age, active handling time, and owner-wait time answer different questions. Sample by age band and consequence rather than only by the oldest records. Include items that appear quiet, because an absence of activity may mean stable waiting, a missed acknowledgement, or a broken integration. Preserve the source event and calculate derived measures in a separate field so another reviewer can reproduce every interval.`,
      `Facts and analysis must stay distinct. A record can prove that a case remained in a queue for five days; it cannot prove that the Philippines specialist caused the delay. A long pause may reflect missing customer evidence, an unavailable approver, a policy ambiguity, or a system outage. For each sampled item, classify the observable state first, then identify the next accountable decision and the evidence supporting that interpretation. Have a second reviewer classify a subset without seeing the first result. Disagreement is useful evidence of unclear status definitions or incomplete context. Do not improve the apparent metric by changing a date, closing a waiting item, or moving an exception into a less visible category.`,
      `A delegated specialist can verify timestamps, apply approved age bands, identify missing inputs, prepare an escalation packet, and remind a named owner under a written rule. The role should not silently reprioritize work, promise a new customer outcome, approve a refund, make a security judgment, or close an item merely because it is old. The owner decides consequence and priority when the evidence does not establish an approved path. This boundary is particularly important in offshore work spanning time zones: a queue may be unattended locally while the business owner still retains the only authority to release a consequential action. The report should show where that authority is available and where it is absent.`,
      `Analyze age alongside consequence, not as a standalone leaderboard. Useful strata include customer-facing versus internal work, routine versus exception, complete versus incomplete evidence, and delegated action versus owner decision. Report counts and denominators for each stratum. Pair age with rework, reopened items, missed next actions, unresolved approvals, and correction notes. A falling backlog can be misleading if closure behavior changed; a rising backlog can reflect better detection of previously hidden work. If a new intake rule is introduced, compare like cohorts and mark the effective date. A simple before-and-after average is weak evidence when demand, policy, staffing, or system behavior changed simultaneously.`,
      `The evidence scope has limits. A short sample can miss seasonal demand, outages, or rare high-consequence events. Exported timestamps may not preserve the original system history, and a customer may wait outside the queue after an internal status says complete. Privacy constraints may limit the detail that can be copied into a research register; use minimum necessary identifiers and link to the approved source. NIST and CISA guidance support treating security, access, and risk context as part of an operating process, while SBA guidance provides general supervision context. None of these sources creates a benchmark for this company or proves that a particular queue design will perform.`,
      `A sound finding names the intervention it can support and the evidence that would overturn it. If owner-wait time dominates, define review windows or backup authority before expanding preparation capacity. If incomplete intake dominates, improve the entry condition. If age is concentrated in a high-consequence exception class, narrow the role and make escalation visible. If timestamps cannot be reconciled, fix source stewardship before interpreting a trend. Keep the original sample, definitions, and exclusions so a later study can distinguish genuine change from changed measurement. The specialist contributes reliable classification and evidence; the authorized owner chooses the risk response.`,
      `Evidence-led conclusion: queue age becomes decision-relevant when it is tied to state, consequence, evidence completeness, and accountable next action. For Philippines outsourced operations, the safest use of an aging study is to expose where a delegated lane stops and where owner coverage must begin. It does not justify a universal turnaround claim, a staffing promise, or a judgment about a person or location. Re-run the sample after a material policy, system, calendar, access, or case-mix change. Sources: ${commonSources.join('; ')}. Retrieved 2026-08-21.`,
      `A practical research record should therefore preserve the queue snapshot, the sampling rule, the calculation logic, and the reviewer notes. Record why an item was excluded and whether the exclusion could bias the result. Keep separate fields for “old,” “blocked,” “awaiting owner,” and “no next action”; they are not interchangeable. When the report recommends a small pilot, specify the one changed control, the comparable cohort, the review owner, and the stopping condition. This makes the conclusion testable without pretending that elapsed time alone explains an operational outcome.`
    ]
  },
  {
    slug: 'philippines-outsourced-handoff-continuity-evidence-study', date: '2026-08-21', hero: '/research-aug21-heroes/handoff-continuity-evidence.png',
    title: 'Handoff continuity evidence in Philippines support operations', excerpt: 'What proves that outsourced work remains owned across shifts, absences, and time-zone boundaries?',
    body: [
      `Research question: what evidence proves that a Philippines support item remains owned when it crosses a shift, absence, holiday, or time-zone boundary? A handoff message is not the same as continuity. Continuity requires a reproducible current state, a permitted next action, a named receiver, and a route for decisions outside the delegated role. The study scope is one queue and a declared sample of ordinary, incomplete, escalated, and reopened items. It evaluates the handoff record, not the personality or effort of the people involved. The buyer decision is whether the current transition design preserves accountability without requiring the receiver to reconstruct a long conversation or invent authority.`,
      `Define a handoff event before reviewing outcomes. Capture the last verified state, the source record, evidence still needed, the next permitted action, the next review point, the receiving role, and the escalation destination. Include the local time and the business time used by the owner. Sample accepted handoffs and failures, including items that appeared to transfer successfully but later reopened. A forwarded message may be a source artifact, but it should not be counted as acceptance until the receiving role can identify the state and next action. Record missing acknowledgements separately from missing context; they require different interventions.`,
      `Treat the record as facts first and interpretation second. A timestamp shows when a packet was sent, not that the receiver understood it. An opened ticket shows access, not authority. A returned item shows that the receiving lane could not complete the next step, but not whether the cause was poor preparation, missing policy, unavailable evidence, or an owner decision that was never assigned. Ask a reviewer unfamiliar with the original thread to reconstruct a sample using only the handoff packet and approved source. The questions they cannot answer are direct evidence about handoff completeness. Keep alternative explanations until the sample distinguishes them.`,
      `A Philippines support specialist may prepare the transition summary, update agreed fields, identify dependencies, and send a reminder under a documented operating rule. They should not change priority, approve a sensitive action, extend a customer commitment, alter permissions, or declare completion because the normal owner is unavailable. The business owner must define backup authority, escalation thresholds, and what happens when no receiver acknowledges the item. This role boundary reduces the temptation to make the handoff appear successful by allowing unauthorized improvisation. It also gives the buyer a clear test: can the next person continue routine work while consequential decisions remain with the authorized owner?`,
      `Measure continuity with more than acknowledgement rate. Report time to acknowledgement, time to next permitted action, missing-evidence rate, repeated clarification, reassignment, reopened work, and unowned exceptions. Segment by transition type, case consequence, and whether the item was complete at transfer. If a new packet design is tested, compare comparable cohorts and record concurrent changes such as training, demand spikes, outages, or new owners. A shorter handoff may be worse if it removes evidence; a longer packet may be worse if the important decision is buried. Review both usability and control preservation.`,
      `The study cannot prove that a particular shift model or geography causes continuity failure. Logs may omit verbal decisions, links may expire, and a case can change while the packet is in transit. Privacy and security controls constrain what should be copied across systems. NIST and CISA materials provide useful control questions about access, risk, and recovery, while SBA material provides general management context; none establishes a company-specific handoff standard. State the sample size, exclusions, event definitions, and unresolved gaps. A finding should expire or be revisited after a system migration, policy change, or new coverage arrangement.`,
      `Evidence-led conclusion: a reliable offshore handoff is demonstrated by state, source, authority, next action, and acceptance evidence together. For Philippines support operations, the safest improvement may be a smaller packet with clearer fields, a named backup reviewer, or a stricter stop condition rather than more messages. If the receiver can reproduce routine work but cannot identify the owner decision, the process is partially continuous and should be reported that way. Sources: ${commonSources.join('; ')}. Retrieved 2026-08-21.`,
      `The final decision brief should include one successful and one failed transition, with the records anonymized to the minimum necessary level. Explain which field prevented reconstruction, which authority was missing, and what small change will be tested. Retain the old definition and its effective date so future comparisons do not erase the baseline. A continuity study is valuable precisely because it makes invisible ownership gaps visible; it should not become a ranking of who sends the most complete-looking message. Also record whether the receiver had the required system access, whether the source was current, and whether the next action was routine or consequential. Those distinctions help separate a handoff design defect from an access defect or a missing owner. If the same gap appears after a reminder, the next experiment should change the record or authority path rather than increase message frequency. Recheck after a holiday pattern, role change, or system migration, because continuity evidence is conditional on the operating context.`
    ]
  },
  {
    slug: 'philippines-outsourced-reviewer-agreement-evidence-study', date: '2026-08-21', hero: '/research-aug21-heroes/reviewer-agreement-evidence.png',
    title: 'Reviewer-agreement evidence for Philippines outsourced support quality', excerpt: 'How can a buyer tell whether a support quality rubric produces consistent judgments across reviewers?',
    body: [
      `Research question: does a quality rubric lead different reviewers to reach the same bounded judgment about Philippines outsourced support work? Agreement is not proof that a rubric is correct, and disagreement is not proof that an operator failed. The study examines whether reviewers can apply defined criteria to the same evidence, distinguish a defect from an approved exception, and state when owner judgment is required. Scope one process, one rubric version, one observation period, and a sample that includes routine work and boundary cases. The result should inform training, rubric revision, sampling, or role boundaries, not produce an unsupported score for a person or supplier.`,
      `Write the rubric before selecting the sample. Each criterion needs an observable unit, an evidence source, an acceptable range or condition, and a disposition rule. Avoid labels such as “good communication” unless the record defines what can be inspected. Stratify the sample by channel, case type, consequence, completeness, and outcome so easy cases do not dominate. Give reviewers the same evidence packet and record independent judgments before discussion. Preserve the rubric version, reviewer role, time spent, missing evidence, and reason for any override. A single blended agreement percentage can conceal that reviewers agree on routine formatting but diverge on consequential exceptions.`,
      `Separate observation, classification, and decision. The record may show that a response included a source link, but the reviewer still must decide whether the link supports the exact statement. Two reviewers may agree that evidence is missing while disagreeing about whether the item should stop or escalate. That disagreement reveals a role or rubric question, not automatically a quality failure. Review the disagreement log for ambiguous language, conflicting policies, inaccessible sources, and examples that do not cover the case. Do not coach reviewers toward agreement before recording their independent views; doing so turns measurement into consensus theater.`,
      `A Philippines support specialist can prepare work against the approved rubric, attach the relevant evidence, flag uncertainty, and request a review of a boundary case. They should not alter the rubric, waive a criterion, hide a defect, or convert a disputed classification into a customer commitment. The quality owner decides the standard, while an authorized business owner decides exceptions with customer, financial, privacy, security, or policy consequences. This separation lets a buyer test whether the role is receiving usable instructions rather than treating every disagreement as a hiring issue.`,
      `Analyze agreement by criterion and case class. Use counts, denominators, and a clear rule for missing evidence. Where appropriate, calculate a chance-adjusted statistic, but explain its assumptions and do not substitute it for the disagreement log. Compare false approvals and false returns on a known-answer subset if such a subset can be defined responsibly. Test the rubric with a small calibration round, revise only through the accountable owner, and then run a fresh sample. A rising agreement rate after examples are added may reflect genuine clarity or reviewers learning the answer key; both context and independent evidence matter.`,
      `Limitations are material. Reviewers may share an unstated interpretation, the sample may underrepresent rare risk, and the evidence packet may omit the customer context needed for a fair decision. Agreement cannot establish business impact, predictive validity, or a universal quality benchmark. NIST and CISA guidance can inform questions about traceability, access, and risk, while SBA guidance can inform supervision questions. These sources do not validate this rubric. Minimize personal information in calibration examples and retain only the evidence needed for a reproducible judgment.`,
      `Evidence-led conclusion: a quality rubric is useful for outsourced support only when its judgments are observable, its disagreement is preserved, and its boundary cases have an owner path. For Philippines operations, reviewer agreement can show where instructions or examples need improvement, but it cannot by itself prove that work is accurate, safe, or commercially successful. Keep the rubric version and re-test after policy, product, source, or reviewer changes. Sources: ${commonSources.join('; ')}. Retrieved 2026-08-21.`,
      `The recommended output is a calibration record with the question, criteria, independent classifications, disagreement reasons, final disposition, and next rubric change. Report the small number of cases that required owner judgment instead of forcing them into a routine score. If the same ambiguity returns, that recurrence is stronger evidence for a policy clarification than a lower score is evidence against the operator. A useful quality study improves the boundary between preparation, review, and decision. Before adopting a revised rubric, test whether a new reviewer can apply it from the written examples without private coaching. Keep a small set of stable examples for later comparison, while adding new boundary cases when the process changes. If reviewers agree only after seeing the expected answer, label that result as calibration rather than independent agreement. The distinction protects the owner from mistaking familiarity with an answer key for evidence that the rule is understandable in live work.`
    ]
  },
  {
    slug: 'offshore-process-change-evidence-research', date: '2026-08-21', hero: '/research-aug21-heroes/process-change-evidence.png',
    title: 'Process-change evidence in offshore operations research', excerpt: 'Which records show that an offshore workflow change was approved, effective, and safe to interpret?',
    body: [
      `Research question: how can an offshore operations team distinguish an approved process change from a suggestion, experiment, or local workaround? This distinction matters when a Philippines support lane is asked to follow instructions that change over time. A message in a chat channel may be informative without being an authorization. The study follows one workflow through a defined change period and examines the proposal, decision authority, effective date, affected roles, source-of-truth update, training evidence, and post-change observation. It does not judge whether a change was strategically wise; it asks whether a later reviewer can establish what changed and who approved it.`,
      `Define the change record before sampling. At minimum, capture the old rule, proposed rule, reason, risk or dependency, approver, effective date, affected queue, source location, communication path, and rollback or exception instruction. Sample approved changes, rejected proposals, temporary experiments, and recurring local workarounds. Include one item where the source was updated late. The distinction between “proposed” and “effective” should be a field, not an inference from message order. Preserve the original record and the current version so a research reader can reconstruct the transition without relying on memory.`,
      `Facts must not be upgraded into conclusions. A new instruction posted on a date proves publication, not approval. A changed form proves implementation activity, not that every operator saw or understood the change. A lower rework count may follow the change, but it does not prove causation without considering demand, case mix, staffing, and other concurrent edits. Record observations separately from analysis and identify what would falsify the interpretation. If two sources disagree, route the conflict to the owner instead of selecting the most recent message as the rule.`,
      `A delegated specialist can locate the current approved instruction, compare it with the prior version, note effective dates, and identify records affected by the transition. They should not self-authorize a workaround, rewrite a policy, broaden access, or announce a consequential exception. The owner of the process retains authority to approve and retire rules. A manager or designated reviewer should own the change log and the decision about whether a pilot may become standard. This boundary protects the business from silent drift while still allowing the offshore lane to surface practical implementation evidence.`,
      `Evaluate a change through a staged evidence design. First test whether the record is complete and the source is discoverable. Next sample implementation records for correct version, acknowledgement, and permitted use. Then compare a defined set of outcomes such as rework, returned items, clarification cycles, or exception routing, while keeping counts and denominators visible. Do not treat a post-change improvement as proof if the eligible population changed. Record outages, training, demand spikes, and policy changes. If a rollback occurred, study it as evidence about the boundary conditions rather than hiding it as failure.`,
      `The evidence has limitations. Version histories may be incomplete, chat decisions may be difficult to preserve, and people may follow a local copy after the canonical instruction changes. A process-change study cannot establish that an offshore team caused or prevented a business outcome. NIST and CISA materials help frame risk, traceability, access, and recovery questions; SBA material helps frame management and supervision questions. They do not certify a workflow or create a change-control requirement for this company. Keep copied records minimal where they contain customer or commercial information.`,
      `Evidence-led conclusion: process-change evidence is trustworthy when approval, effective date, source version, affected role, and observed implementation are linked. For offshore operations, the most useful result may be that a proposed improvement is not yet safe to treat as a rule. That finding protects the owner from accidental policy drift and gives the delegated lane a clear stop condition. Sources: ${commonSources.join('; ')}. Retrieved 2026-08-21.`,
      `The final report should show one change that completed the full path and one that stopped at proposal or required owner clarification. State the smallest corrective action: update the source, name an approver, retire a local copy, or define the experiment window. Repeat the review after a material system, policy, access, or role change. A reliable change log is not bureaucracy for its own sake; it is evidence that the work being delegated is governed by a current and reviewable rule. Include the local interpretation that was prevented, if any, and explain how a routine operator should recognize the boundary next time. A change that improves speed but weakens traceability should not be accepted as a clear win. Conversely, a temporary increase in review can be evidence that the new control is detecting exceptions honestly. The owner should choose the acceptance threshold before observing the result, so the research does not drift toward whichever measure looks favorable after implementation.`
    ]
  },
  {
    slug: 'offshore-claim-to-source-verification-evidence-study', date: '2026-08-21', hero: '/research-aug21-heroes/source-verification-evidence.png',
    title: 'Claim-to-source verification for offshore research support', excerpt: 'How should an offshore research lane test whether a source actually supports the wording a buyer may rely on?',
    body: [
      `Research question: does each material claim in an offshore research brief have a source that supports its wording, population, period, and certainty? A list of reputable URLs is not enough. A source can be authoritative yet irrelevant to the sentence written from it, or a general observation can be inflated into a guarantee about a Philippines support role. This study examines a bounded brief, its claim register, and a sample of headline and supporting statements. It is a verification method, not legal advice, a market forecast, or a guarantee of an outsourcing outcome. Its decision purpose is to identify which claims are publishable, which need narrower language, and which should be removed.`,
      `Start with the claim rather than the bibliography. Record the exact sentence, claim type, population, geography, period, denominator, source publisher, URL, relevant section, access date, evidence strength, and reviewer disposition. Classify sources as official government material, recognized standards, research literature, official organizational guidance, or secondary commentary. Check whether a statistic has a defined sample and whether a qualitative statement is being treated as quantitative evidence. Preserve short notes and links rather than copying large passages. When a page changes or disappears, mark the claim as needing review; do not silently replace it with a vaguely related page.`,
      `Verification requires separating what the source says from what the writer infers. A government page may describe a control principle without proving that a company follows it. A study of one population may not support a claim about every offshore team. A source date may establish publication timing but not current validity. Ask a second reviewer to decide whether the source supports the sentence as written and to identify any missing caveat. Record disagreement at claim level. If the claim can be supported only after changing “will” to “may,” or narrowing the population and period, make that revision visible rather than presenting the original certainty.`,
      `An offshore research specialist may locate sources, capture relevant evidence, compare definitions, maintain the claim register, and flag unsupported wording. They should not invent a citation, quote out of context, fabricate a statistic, or present a business result that the evidence does not measure. An authorized owner or editor decides the publication standard and whether a claim is important enough to remove. This boundary is central to a useful support role: the specialist reduces search and verification work while keeping judgment and public accountability with the person who can authorize the final statement.`,
      `Test the method with a complete set of headline claims and a random sample of supporting claims. Report supported, partially supported, unsupported, stale, inaccessible, and out-of-scope classifications with counts and denominators. Review claims that rely on several sources as a chain; one source may support context while another supports the narrow fact. Compare reviewer agreement and correction time. A high citation count can coexist with weak evidence if links are decorative. A shorter brief with direct claim-to-source fit is stronger than a longer brief built from generic citations.`,
      `The method has limits. Web pages change, archives may be inaccessible, terminology differs across studies, and a source may omit the operational detail a buyer actually needs. Verification cannot prove that a recommendation will work in a particular business, nor can it replace legal, security, privacy, or procurement review. NIST, CISA, and SBA materials provide useful context for control and management questions, but they do not validate any company-specific statement. Minimize personal and confidential information in research notes and use approved storage and access.`,
      `Evidence-led conclusion: offshore research quality depends on claim-to-source fit, scope, and explicit uncertainty rather than the number of URLs attached. For a Philippines operations brief, a safe result may be a narrower claim, a stated evidence gap, or a request for owner confirmation. Those are successful verification outcomes because they prevent unsupported certainty from entering a buyer decision. Sources: ${commonSources.join('; ')}; https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business. Retrieved 2026-08-21.`,
      `The final register should preserve the original claim, the reviewer result, the edit or removal decision, and the access date. Recheck material claims after a source update, policy change, or new publication date. When a source cannot support a sentence, do not reward the draft for retaining the citation; reward it for making the evidence boundary honest. That practice gives an offshore research lane a clear role and gives the owner a defensible basis for deciding what belongs in public copy. For high-consequence claims, add a second check that asks whether the evidence is current, whether the language implies a guarantee, and whether the source concerns the same population and decision. Keep those checks separate from grammar editing. A polished sentence can still exceed its evidence. The strongest research packet shows removed claims as well as retained claims, because the removal decision demonstrates that the reviewer tested scope rather than merely collecting links. Revisit the register when a source changes its definitions or when the business begins using the brief for a different decision.`
    ]
  }
];
